# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5f58e5caa1e62b0452f421ddf92656eddeb278d723e0319d8e104206efd25395ec63081d32b86c9b4f6654c3543ef9fdc1f10660a2106fd1d46d67858f99eaa

test:
  secret_key_base: 44b2d5aa2a64af71488cc2ecbc3fc40cd4295bb425f7b49b272deef4438ea4a2076d2ffbaf012ad60c1530593750d22427eaa19fcd4cfa3c2b2783a88ab7f979

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
